import logging
from typing import Tuple, List, Dict, Any

from planner_agent import generate_research_plan
from arxiv_search import search_papers
from vector_store import add_documents
from retriever import retrieve_context
from analysis_agent import analyze_papers

# Configure logging for the pipeline
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def run_research_pipeline(user_query: str, max_papers_per_query: int = 3, top_k_context: int = 5) -> Tuple[List[Dict[str, Any]], str, dict]:
    """
    Executes the full end-to-end autonomous research pipeline driven by a Planner Agent.
    
    Args:
        user_query: The user's original research question.
        max_papers_per_query: Max papers to fetch *per optimized search query*.
        top_k_context: Number of most relevant paper chunks for the final synthesis.
        
    Returns:
        A tuple containing:
            - A list of dictionaries representing ALL fetched research papers.
            - A markdown string containing the final generated research report.
            - The plan dictionary generated by the Planner Agent.
    """
    logging.info(f"--- Starting Autonomous Research Pipeline for: '{user_query}' ---")
    
    # Step 1: Planner Agent understands and breaks down the task
    logging.info("Step 1: Planner Agent is decomposing the research question...")
    try:
        plan = generate_research_plan(query=user_query)
        search_queries = plan.get("search_queries", [user_query])
        logging.info(f"Planner identified queries: {search_queries}")
    except Exception as e:
        logging.error(f"Planner failed, falling back to direct query. Error: {e}")
        plan = {"understanding": "Direct fallback", "search_queries": [user_query]}
        search_queries = [user_query]
        
    # Step 2: Search papers from ArXiv based on Planner's sub-queries
    logging.info("Step 2: Searching ArXiv using optimized sub-queries...")
    all_papers = []
    seen_links = set() # Prevent duplicate paper ingestion
    
    for sq in search_queries:
        logging.info(f"  -> Executing search for: '{sq}'")
        results = search_papers(query=sq, max_results=max_papers_per_query)
        for p in results:
            if p["pdf_link"] not in seen_links:
                all_papers.append(p)
                seen_links.add(p["pdf_link"])
                
    if not all_papers:
        logging.warning("No papers found on ArXiv for any of the generated queries. Pipeline terminating.")
        return [], "No research papers found to analyze.", plan
        
    logging.info(f"Successfully retrieved a total of {len(all_papers)} unique papers.")

    # Step 3: Store papers in ChromaDB vector database
    logging.info("Step 3: Storing papers in Vector Database...")
    add_documents(all_papers)
    
    # Step 4: Retrieve relevant context using RAG
    logging.info(f"Step 4: Retrieving top {top_k_context} relevant context chunks against original query...")
    # Note: We query the DB against the original dense user_query to pull the best holistic chunks
    context = retrieve_context(query=user_query, top_k=top_k_context)
    
    if context == "No relevant context found in the vector database.":
        logging.warning("Failed to retrieve context from the database.")
        return all_papers, "Failed to retrieve context for analysis.", plan
        
    # Step 5 & 6: Send context to Gemini and generate final research report
    logging.info("Step 5 & 6: Synthesizing context and generating final research report via Gemini...")
    try:
        report = analyze_papers(research_question=user_query, context=context)
        logging.info("Pipeline completed successfully.")
        return all_papers, report, plan
    except Exception as e:
        logging.error(f"Failed to generate report: {e}")
        return all_papers, f"An error occurred during report generation: {e}", plan

# ==========================================
# Example Usage
# ==========================================
if __name__ == "__main__":
    # Ensure GOOGLE_API_KEY is set in your environment variables for this to work
    test_query = "Applications of Multi-Agent reinforcement learning in robotics"
    
    try:
        fetched_papers, generated_report, research_plan = run_research_pipeline(
            user_query=test_query, 
            max_papers_per_query=2,   
            top_k_context=3   
        )
        
        print("\n" + "="*50)
        print("PIPELINE EXECUTION COMPLETE")
        print("="*50 + "\n")
        
        print(f"Total Unique Papers Fetched: {len(fetched_papers)}")
        print("\n" + "="*50)
        print("GENERATED RESEARCH REPORT")
        print("="*50 + "\n")
        print(generated_report)
        
    except Exception as main_e:
        print(f"Pipeline execution failed: {main_e}")
